
#Planes settings
[general]
	#planes crash on bad landings
	planeCrush = true
	#easier flight mode, disables the extreme movements
	easyFlight = false
	#For controllers, a threshold for the joystick movement of the plane
	#Range: 0 ~ 90
	turnThreshold = 20
	#Ticks of flying per one coal (furnace planes)
	#Range: > 0
	flyTicksPerCoal = 600
	#can players steal planes
	plane_heist = true

